### ISSUE TITLE
Upload unix_ar in PYthon Package Index

### ISSUE THREAD

**Issue by vit1251** [remram44/unix_ar#1]
Can I ask you add **unix_ar** package on PyPi server?

It make simplify using your package. Example shell command will installation your package:

```
# pip install unix_ar
```

Thanks.

**Comment by remram44** [comment]
Hi Vitold,

I am unlikely to release that on PyPI since it is unfinished and I won't spend more time on it. During development it appeared obvious that AR is too limited a format for my needs, and TAR seems superior on all aspects (or better yet ZIP).

There exist some extensions to the AR format lifting some of the filenames limits but I don't want to track those down. There are other packages on PyPI that support AR in various degrees, you should probably turn to those 

I will update the README to reflect the status of this repository.
